### PR TITLE
Sessions pages in admin section

### PR DESCRIPTION
**Pull request by adrianbanks**
This is based on #270 as it shares a lot of the styling changes, so that should be merged first.

Style the session details, edit and delete pages to match the newly-created users pages.

### CODE REVIEW

**Comment by alastairs** [comment]
Where are the tests for the new actions? I think I might have missed this in the user's admin pages too... :frowning:

**Comment by adrianbanks** [comment]
I couldn't see what to test other than the implementation when I looked at it originally. Looking at it again, I think there is some behaviour for some of the actions, but not all. Any suggestions?

**Comment by alastairs** [comment]
Well, off the top of my head, there's the interactions with the repositories to verify: ensuring the controller delegates correctly.

**Comment by adrianbanks** [comment]
> there's the interactions with the repositories to verify

Hmm, feels a bit like testing the implementation. I'll take a look at see what I can do.

**Pull request merged**
