### PR TITLE
Adding Techsmith logo

### PR DESCRIPTION
**Pull request by philpursglove**

### CODE REVIEW

**Comment by adrianbanks** [comment]
The logo is a bit blurry. Is that the best quality version you have?

**Comment by philpursglove** [comment]
That's off their hi-res image files off [their website](http://www.techsmith.com/download-logo.html), but it's losing some of its sharpness when I scale it up to 280x200 :-(

**Comment by adrianbanks** [comment]
I'll have a play with it to see if I can get it any sharper.

**Comment by adrianbanks** [comment]
New logo:

techsmith

This is the correct dimensions for the sponsors pages, so can just replace the one you have in this pull request.

**Pull request merged**
