### PR TITLE
Make the voting buttons consistently styled like the other action items

### PR DESCRIPTION
**Pull request by adrianbanks**
:warning: **Do not merge yet - not ready**

The voting button had its own style, whereas it should have been styled the same as the other action items on a session.

### CODE REVIEW

**Comment by alastairs** [comment]
This appears to have had the side effect of indenting the voting button even further. Is this desirable?

**Comment by adrianbanks** [comment]
Not sure what happened there - a file went missing from the history. Should be ok now.

**Comment by alastairs** [comment]
:+1: Looks good, will merge tomorrow.

**Comment by ninjaferret** [comment]
You have checked that the Javascript still works with the voting buttons haven't you? It requires the voting class to identify the HTML element to replace with the new form rendered by the status partial

Also, I wanted to make the voting stand out, I thought the other actions were fine being more subtle

**Comment by alastairs** [comment]
> [The JavaScript] requires the voting class to identify the HTML element to replace with the new form rendered by the status partial

Ah, that will probably be the cause of #142, then.

@ninjaferret: I checked it visually as on reading the pull request I thought, like you, that @adrianbanks had altered the styling of the button too, but it's just a change to tweak the alignment of the control AFAICT. 

I guess the lesson here is that some QUnit (or similar) tests would be good...

**Comment by adrianbanks** [comment]
I'll check this and update if necessary. I'm not sure how it can be the cause of #142, as this has not been merged anywhere yet.

**Comment by ninjaferret** [comment]
just as long as it retains the "voting" class then I don't mind too much,
even if the voting class isn't used for styling, if it doesn't the
Javascript won't work. Or you can change the javascript and the
Status.cshtml to replace the form based on the new HTML that is produced
and not provide the span

Looking at the database #142 was working but the cookie wasn't being saved
so the status partial didn't know you had voted for it so the redirect to
the status returned a voting form again

On 30 April 2013 10:17, Alastair Smith notifications@github.com wrote:

> [The JavaScript] requires the voting class to identify the HTML element to
> replace with the new form rendered by the status partial
> 
> Ah, that will probably be the cause of #142https://github.com/dddeastanglia/DDDEastAnglia/issues/142,
> then.
> 
> @ninjaferret https://github.com/ninjaferret: I checked it visually as
> on reading the pull request I thought, like you, that @adrianbankshttps://github.com/adrianbankshad altered the styling of the button too, but it's just a change to tweak
> the alignment of the control AFAICT.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dddeastanglia/DDDEastAnglia/pull/141#issuecomment-17217080
> .

## 

Ian Johnson

**Comment by ninjaferret** [comment]
It wasn't, purely the cookie expiring at the end of the wrong month #143.
Voting is working again on staging

On 30 April 2013 10:24, Adrian Banks notifications@github.com wrote:

> I'll check this and update if necessary. I'm not sure how it can be the
> cause of #142 https://github.com/dddeastanglia/DDDEastAnglia/issues/142,
> as this has not been merged anywhere yet.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dddeastanglia/DDDEastAnglia/pull/141#issuecomment-17217361
> .

## 

Ian Johnson

**Comment by alastairs** [comment]
Looks like there's still a couple of tweaks to make to this before it can be merged.

**Comment by alastairs** [comment]
Is this able to be merged yet?

**Comment by adrianbanks** [comment]
No. Still got some odd behaviour happening, and there is more important stuff at the moment. I'll get round to it.

**Comment by alastairs** [comment]
This seems to have stalled, and there's only two weeks left in voting now. Is it worth keeping this open any longer?

**Comment by adrianbanks** [comment]
Yes, I will fix it once the other two pull requests have been dealt with.

**Pull request closed without merging**
