### PR TITLE
Add JsonConvertWrapper

### PR DESCRIPTION
**Pull request by philpursglove**
Adds JsonConvertWrapper to fix JsonConvert visibility weirdness on Phils machine.

### CODE REVIEW

**Comment by alastairs** [comment]
Do we actually want this in the site...?

**Comment by adrianbanks** [comment]
Not really, but it is hampering Phil from working on the site.

**Comment by alastairs** [comment]
Yeah, so could we leave it as a temporary thing for @philpursglove today, rather than making it a permanent thing that is otherwise unnecessary?

**Comment by philpursglove** [comment]
That's fine, but it implies the existence of another solution which is non-temporary.

**Comment by alastairs** [comment]
Fixed without code changes.

**Pull request closed without merging**
