### PR TITLE
Add Tekpub to the sponsors page

### PR DESCRIPTION
**Pull request by adrianbanks**
3rd time lucky :smiley:

### CODE REVIEW

**Comment by alastairs** [comment]
> 3rd time lucky :smiley: 

Lol, not quite. It needs to be rebased on to 6644f87: the parent of your commit is 0641bf7, which is the merge of #99 that went wrong.

**Comment by adrianbanks** [comment]
Rebased onto production.

**Comment by alastairs** [comment]
Build looks to be still failing?

**Comment by adrianbanks** [comment]
Don't know why. I've rebased this onto staging, and I haven't added the generated files so they must be there on the staging site.

**Comment by alastairs** [comment]
Ok, looking at the log in SourceTree, this looks ok. The manual merge is because there are conflicts to be resolved (in `DDDEastAnglia.csproj` and `_Layout.cshtml`), but both are auto-resolved by git. Checking the diffs in the merge commit indicates that the resolution has happened correctly.

The reason the TeamCity build information isn't appearing here is because it can't build this pull request (the watched `/merge` ref isn't available because the pull request can't be merged via GitHub). What I said before about this not building on TeamCity is therefore wrong: the build result I was reporting was for an older version of the commit in this pull request.

Will push this into staging now so it can make it into production as part of the next promotion.

**Pull request merged**
