### PR TITLE
Upgrade to Bootstrap v3.1

### PR DESCRIPTION
**Pull request by alastairs**
Use the latest version of Bootstrap. I've followed the [migration guide](http://getbootstrap.com/migration/) for Bootstrap 2.x users. 
## TODO
- [x] Pull in Bootstrap from NuGet
- [x] Complete the migration
- [ ] Per the comment in 1ee9a7a, port the customisations to a DDDEA theme.

### CODE REVIEW

**Comment by adrianbanks** [comment]
Are you doing Font Awesome at the same time?

**Comment by alastairs** [comment]
No, I was going to do that in a different pull request, as it's a different library.

**Comment by adrianbanks** [comment]
But you are doing it, which is what I was really asking about :smile:

**Comment by alastairs** [comment]
Oh - no, I'm not yet. I haven't made a start on it, so feel free to take it on yourself if you want :smile:

**Comment by adrianbanks** [comment]
I think this will be best left until after this year's conference as the site is now in a "live" state. It will also allow us to integrate any changes to the styling with the new styling in the admin section.

**Comment by alastairs** [comment]
Agreed. The upgrade is a pretty epic change, which is why I gave up on it. I've got a few ideas from my current project at work on how to improve things in an incremental manner, which I will try to put in place during this year's conference, and hopefully that will then make the upgrade to Bootstrap 3 a bit easier (and perhaps Bootstrap 4 will be out by then?!?!).

**Pull request closed without merging**
