### PR TITLE
Fix #96: Add a new Layout for the Admin Area.

### LINKED ISSUE #96: Admin Area is b0rked.
I tried visiting http://dddeastaging.azurewebsites.net/admin/adminhome as a newly-registered user, and got the standard unhelpful YSOD (Runtime Error, an error occurred, set customErrors to off, etc.).

If the user is not in the Admin role, a 404 Not Found response should be returned.

### PR DESCRIPTION
**Pull request by alastairs**
I've included a start of a new layout for the Admin Area, but it will need more work in future.

This fixes the immediate issue, but there's a problem with the Create Session link in the admin area: its using the Admin Route and so 404s. We can at least access the admin pages again.

**Note:** This builds on #107, so **do not merge** until that has gone in.

### CODE REVIEW

**Comment by alastairs** [comment]
I'm just rebasing this to make it easier to merge and verify.

**Comment by alastairs** [comment]
Although GitHub is saying it can't auto-merge this, there are no manual conflicts to resolve: all are auto-resolved by git.

**Comment by alastairs** [comment]
Is this ok to merge @adrianbanks @ninjaferret?

**Comment by adrianbanks** [comment]
It looks ok. One question though: why is the "Conference Admin" a link that goes nowhere?

**Comment by alastairs** [comment]
It's a temporary URL. I'll replace it with the proper URL in a mo.

**Comment by alastairs** [comment]
This is good to merge now, diffs verified.

**Comment by adrianbanks** [comment]
The log out link on the drop down menu has lost its style (position and hover).

**Comment by alastairs** [comment]
Good catch.

**Comment by adrianbanks** [comment]
Happy to merge as is though, as I've got a branch based off this and I'd like to rebase it.

**Comment by alastairs** [comment]
Shouldn't be too tricky to fix. Will take a quick look and update if I can (will probably be a bit of a hacky fix).

**Comment by alastairs** [comment]
Fixed with a copy-paste job. See f0d7190 for details of a proper fix; I didn't put that in because it would have been a larger change and require a bit of trial-and-error to work out what in Site.css is site-specific and what is a generally-applicable Bootstrap override.

**Pull request merged**
