### PR TITLE
Remove excess padding from the bottom of a speaker

### PR DESCRIPTION
**Pull request by adrianbanks**
This had the effect of having an odd block of whitespace at the top of each speaker (except the first) when in a list, especially when coupled with the horizontal rule that we use as a separator.

### CODE REVIEW

**Comment by alastairs** [comment]
How much padding-bottom is rendered now?

**Comment by adrianbanks** [comment]
None in addition to the standard padding applied by bootstrap to the row-fluid class. It looks much better balanced now, as there is equal space both above and below each speaker.

**Comment by alastairs** [comment]
> It looks much better balanced now, as there is equal space both above and below each speaker.

I agree it looks more balanced now, and that 30px is a bit large with the horizontal rule in place, but I think the sessions look a bit cramped and squashed together without _any_ extra whitespace between them. I had a bit of a play around, and changing the style definition to `margin: 10px 0` looks quite nice, giving them a bit more room to breathe.

**Comment by adrianbanks** [comment]
`margin-top: 10px` works ok, I'll go with that. I don't think we should apply margins everywhere - just where we want the extra space.

**Comment by alastairs** [comment]
The same change should also be applied to the Sessions' page, for consistency. I notice that there are two `.speaker` definitions in the file, too: the other is at the bottom of the file.

**Comment by adrianbanks** [comment]
I'll tweak my pull request to do that...

**Comment by adrianbanks** [comment]
Done.

**Pull request merged**
