### PR TITLE
Fix #133: Add the extra parameter to make the links work

### LINKED ISSUE #133: The links to edit/delete a session don't work
They are in the form `Session/Edit?Length=7` and `Session/Delete?Length=7` which is clearly wrong as they should contain the session id. When you click on them, you get a 404 error.

### PR DESCRIPTION
**Pull request by ninjaferret**

### CODE REVIEW

**Comment by alastairs** [comment]
Please could you use a named parameter to make it obvious what this extra parameter is?

**Comment by alastairs** [comment]
Merging manually due to conflicts. Out of interest, why does this fix the problem?

**Comment by ninjaferret** [comment]
FYI It was simply that the ActionLink overload on the page was:

**ActionLink**(string _linkText_, string _actionName_, object _routeValues_, object _htmlAttributes_)

So the _ActionLink("Edit", "Edit", "Session", new { id= Model.Id})_ mapped the string "Session" to the route values and apparently if you pass a string in as route values you get the **length=7** thing. Adding the extra parameter told it to use this overload:

**ActionLink**(string _linkText_, string _actionName_, string _controllerName_, object _routeValues_, object _htmlAttributes_)

I guess I could have removed the controller name to achieve the same thing but this seemed more appropriate given we were deliberately specifying the controller

**Comment by alastairs** [comment]
Ewwwwwwwwwwwwwwwwwwwwww..............

(Thanks for clarifying.)

**Pull request merged**
