### PR TITLE
Adding Microsoft logo to sponsors sidebar and sponsor page

### PR DESCRIPTION
**Pull request by philpursglove**

### CODE REVIEW

**Comment by adrianbanks** [comment]
The image will need resizing down to be the correct dimensions and proportions. It is currently huge.

**Comment by alastairs** [comment]
@adrianbanks It might be simpler for you to fork Phil's change and update the image on his behalf? IIRC, there's a few steps involved: getting the overall size correct, getting the padding around the logo graphic itself correct, ensuring the logo graphic is correctly aligned within the image, optimising the PNG appropriately...

**Comment by philpursglove** [comment]
Yeah, I had a look at it in Paint.net last night - I can size it right in one dimension but not both :-( Or I can go back to Microsoft's marketing people and ask them if they can resize it to 280x200 for us...

----- Original Message -----

**Comment by adrianbanks** [comment]
I'll fork it and resize the image the same as I've done with the others.

**Comment by adrianbanks** [comment]
I've resized the logo on a separate pull request, based off this one.

**Pull request merged**
